# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has_competency',
            name='code_c',
        ),
        migrations.RemoveField(
            model_name='has_competency',
            name='code_u',
        ),
        migrations.RemoveField(
            model_name='has_grade',
            name='code_g',
        ),
        migrations.RemoveField(
            model_name='has_grade',
            name='code_u',
        ),
        migrations.RemoveField(
            model_name='need_competency',
            name='code_c',
        ),
        migrations.RemoveField(
            model_name='need_competency',
            name='code_j',
        ),
        migrations.RemoveField(
            model_name='need_grade',
            name='code_g',
        ),
        migrations.RemoveField(
            model_name='need_grade',
            name='code_j',
        ),
        migrations.AddField(
            model_name='job',
            name='competencies',
            field=models.ManyToManyField(to='JobApp.Competency'),
        ),
        migrations.AddField(
            model_name='job',
            name='grades',
            field=models.ManyToManyField(to='JobApp.Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='competencies',
            field=models.ManyToManyField(to='JobApp.Competency'),
        ),
        migrations.AddField(
            model_name='user',
            name='grades',
            field=models.ManyToManyField(to='JobApp.Grade'),
        ),
        migrations.AlterField(
            model_name='job',
            name='code_j',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Has_Competency',
        ),
        migrations.DeleteModel(
            name='Has_Grade',
        ),
        migrations.DeleteModel(
            name='Need_Competency',
        ),
        migrations.DeleteModel(
            name='Need_Grade',
        ),
    ]
