# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_auto_20160511_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
