# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_auto_20160511_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_city',
            field=models.TextField(default=datetime.datetime(2016, 5, 20, 10, 3, 42, 519978, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='id_city',
            field=models.TextField(default=datetime.datetime(2016, 5, 20, 10, 3, 59, 372244, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
