# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0007_auto_20160520_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_city',
            field=models.CharField(default=b'Lleida', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_looking_for_job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='zodiac_sign',
            field=models.CharField(default=b'Pisces', max_length=20),
        ),
        migrations.AlterField(
            model_name='competency',
            name='name_c',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name_g',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='id_city',
            field=models.CharField(default=b'Lleida', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
