# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0010_auto_20160609_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='competencies',
            field=models.ManyToManyField(related_name='clients', to='JobApp.Competency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='competencies',
            field=models.ManyToManyField(related_name='jobs', to='JobApp.Competency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='grades',
            field=models.ManyToManyField(related_name='jobss', to='JobApp.Grade'),
        ),
    ]
